### ISSUE TITLE
After updating extension to 1.0.10 the page shows "Loading..."

### ISSUE THREAD

**Issue by nshenoy** [Mimeo/VSTSExtension-ActivePullRequests#39] opened 2019-06-10 19:50 UTC
Because we had to change the manifest to include the "vso.build" scope, it caused a certificate update to happen behind the scenes. Unfortunately, users may need to uninstall the extension from their organization and then reinstall it. I apologize for the inconvenience.

**Comment by ITESMEDIA** [comment] 2019-06-10 20:24
Maybe a message indicating how to fix it would great. Thank you!

**Comment by nshenoy** [comment] 2019-06-10 20:41
That's a good idea. Perhaps I can add a cheesy message telling people to contact their admin to uninstall and reinstall if the "Loading..." doesn't disappear.

**Comment by daniefer** [comment] 2019-06-12 13:49
Would this be the source of the 500 network error I see?
```
POST /_apis/WebPlatformAuth/SessionToken
$id | 1
innerException | null
message | HostAuthorizationNotFound
typeName | Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi
typeKey | SessionTokenCreateException
errorCode | 0
eventId | 3000
```

**Comment by sand-head** [comment] 2019-06-12 13:54
yeah, that'd be it. for some reason, after changing scopes and updating the extension, there seems to be a miscommunication between the extension and Azure DevOps when the extension requests a session token, leading to that 500

**Comment by nshenoy** [comment] 2019-06-12 19:07
With #40 the 1.0.11 version of the extension will show a message asking people to uninstall/reinstall the extension. Thanks @ITESMEDIA for the suggestion!

**Comment by evandixon** [comment] 2019-06-12 20:22
Is it possible to wait a little longer before displaying the warning? I see this for a good 1-3 seconds before the list of PRs loads:
![image](https://user-images.githubusercontent.com/2699524/59383590-ce8a7e80-8d25-11e9-8df5-b58b6c6700a8.png)

**Comment by nshenoy** [comment] 2019-06-12 21:06
I'm hoping this is very temporary. The message will be entirely removed in a week or so. The root cause is that changing scopes on an extension causes Azure DevOps to update the extensions certificate on the backend (hence the 500 reported previously). This isn't an issue for new installs, and this is why the uninstall/reinstall "fixes" the problem. I'll be monitoring the telemetry and when I see a good portion of customers reinstall, I'll submit another update disabling the message.

Alternatively, if you would like to submit a PR to delay load the message, go for it. :)

**Comment by tsteenbakkers** [comment] 2019-06-18 05:11
will there be a solution for on premise TFS users? We are using TFS 2018 and with the last update of the extension the warning message appears for us. Re-installing the extension doesn't cause the warning message to disappear

**Comment by rubenmamo** [comment] 2019-06-18 06:16
I reinstalled the extension, it works fine in Chrome, however I get the same error in Internet Explorer in a specific project. In other projects on IE it works well. Anything I can do to help tracing the issue?

**Comment by sand-head** [comment] 2019-06-18 14:05
@tsteenbakkers I don't currently have a tfs server to test this extension on, but I'll try to see if I can get one set up within the next week to see if I can figure out what's going on for you all. no promises! if you could let me know what browser you're using and open your browser's console and paste back any errors it may contain (via screenshot or text, your preference) it could help narrow down the exact issue.

@rubenmamo I sometimes neglect to test this extension in IE, my bad. if you could send us any errors or warnings coming from the console it could help significantly. I also think this might be unrelated to the scope change after having it fail to load on me personally in IE just now, so if you could open a new issue for this I'll do my best to see it fixed ASAP

**Comment by sand-head** [comment] 2019-06-18 14:47
actually, #44 may contain the fix for your IE issue, so I would hold off on creating an issue for it until it's merged and live just in case

**Comment by nshenoy** [comment] 2019-06-18 17:34
#44 has been merged and version 1.0.13 is live now. I also confirmed that IE is fixed. (Thanks @sand-head!) @rubenmamo could you give it a shot?

**Comment by rubenmamo** [comment] 2019-06-19 07:00
@nshenoy @sand-head I can confirm that the IE issue is fixed :) Thanks for the prompt support.

**Comment by tsteenbakkers** [comment] 2019-06-19 07:01
@sand-head : i've tested it on Chrome, Firefox, IE & Edge. all give me the same message. I understand that setting up a TFS server is not a thing which is done easily or w/o effort so appreciate the effort. Since i'm not a web dev i'm entirely confident about using the chrome / firefox console. above all it contains sensitive information regarding our setup. Can i contact you by e-mail or other means in order to help you get the correct console information you're looking for?

I'm not getting any errors (or looking incorrectly). The only stuff is several warnings that go along the lines of `TypeError: Cannot read property pr.number from undefined`

**Comment by sand-head** [comment] 2019-06-19 14:25
@rubenmamo glad to hear it's working for you! thanks for using this extension!

@tsteenbakkers those types of warnings are exactly the thing that I'm looking for! it seems like your version of tfs 2018 doesn't support the `triggerInfo` property found in builds, which is critical for figuring out build status. based off of [this map](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0#api-and-tfs-version-mapping) and what little info I can gather on api versions prior to 4.1, it looks like it is supported in tfs 2018 update 2 or newer, so I would definitely recommend updating tfs if at all possible, but I understand if you are unable. if you're receiving any more warnings similar to that one feel free to share them either here or by email at jeschwei98@gmail.com, though the handiest way for me personally would be to compile any of these JS warnings together and create a new issue.

**Comment by tsteenbakkers** [comment] 2019-06-19 17:01
That would appear to be correct. We have Some parts of the 4.1 API but in general I use 3.0 for day to day work. We are unfortunately unable to update our tfs version ourselves. Besides that we will make the transition to Azure Devops later this year (currently planning migration). 

I will see if I can compile the previous version of your extension and upload it manually with tfx-cli.

So for now I guess no additional action needed. I will try the manual install of the previous version or use another plugin to bridge the gap until we are on azure devops!

**Closed** 2019-10-25 17:52 UTC
