### ISSUE TITLE
Page only showing 3 pull requests

### ISSUE THREAD

**Issue by g6andrew** [Mimeo/VSTSExtension-ActivePullRequests#18] opened 2018-07-16 16:03 UTC
Since the most recent update, the page is only showing 3 PR's, although there are more.

**Comment by Abe-Froman** [comment] 2018-07-16 23:37
We are seeing the same, only noticed for the first time today.

Refreshing the page will display a different set of 3 PRs.

**Comment by Abe-Froman** [comment] 2018-07-17 00:14
After debugging a bit, I suspect this is caused by a breaking change from VSTS. At the point all pull requests are added to the grid, `grid.setDataSource(activePullRequests);`, our activePullRequests object has all PRs in it we'd expect. You can test this yourself by sorting on one of the columns and see that the displayed PRs change.

I'll see if I can raise awareness of this to the VSTS team.

**Comment by g6andrew** [comment] 2018-07-17 16:30
Would setting the grid height to 100% instead of 0px help?

**Comment by Abe-Froman** [comment] 2018-07-17 16:39
No, I don't think so. The `grid-canvas` in the DOM only holds 3 `grid-row` elements so it's not a matter of them being present but not displayed.

**Comment by nshenoy** [comment] 2018-07-18 13:10
Thanks for reporting this issue. We're looking into it and will get back to you soon. I'll rollback the extension to the previous version in a little bit so we can view all PRs again. But it will reintroduce that title bar disappearing bug unfortunately. :(

**Comment by nshenoy** [comment] 2018-07-18 13:16
The extension has been rolled back to an older version. We'll keep this issue posted when we fix the bug. Thanks!

**Comment by nshenoy** [comment] 2018-08-03 13:43
Just an update. @sand-head is working on a fix that we are currently testing out. The extension fixes the previous issues (and looks a bit nicer, too!). Stay tuned for an updated version in the marketplace. Thank you all for your patience!

**Comment by nshenoy** [comment] 2018-08-03 17:20
This has been fixed! The extension has been published under a new Mimeo publisher, with the previous one marked as "deprecated." Please uninstall the old extension and install the new one from here: https://marketplace.visualstudio.com/items?itemName=mimeo-vs-marketplace.mimeo-active-pull-requests . Thanks!

**Closed by nshenoy** 2018-08-03 17:20 UTC
