### ISSUE TITLE
Pull request created under same repository does not get reflected in "All Active Pull Requests"

### ISSUE THREAD

**Issue by mvishwakarma93** [Mimeo/VSTSExtension-ActivePullRequests#19] opened 2018-07-17 09:20 UTC
We have below issue :
1. I have created few PRs for a repository, previously I was able to see all my and teams PR as well under "All Active Pull Requests", but now the list shows all PR`s excluding my PR.
2. Also I need to visit every repositories "Pull Requests" tabs to see the PRs created by me against the specific repository. It never shows me under "All Active Pull Requests".
3. The count for all repositories in "All Active Pull Requests" does not match with the list of PRs shown below it.

![total pr counts](https://user-images.githubusercontent.com/41324738/42808136-30a72348-89d0-11e8-9360-0ccb4906e5df.PNG)

**Comment by nshenoy** [comment] 2018-07-18 13:11
This is a dupe of #18. We'll track the issue there. Thanks!!

**Closed by nshenoy** 2018-07-18 13:11 UTC
